version: "3.2"
services:
  redis-master:
    image: "redis:alpine"
    command: redis-server /data/redis-auth.conf
    volumes:
      - ./auth/master-auth.conf:/data/redis-auth.conf
  redis-slave:
    image: "redis:alpine"
    command: redis-server /data/redis-auth.conf
    volumes:
      - ./auth/slave-auth.conf:/data/redis-auth.conf
    depends_on:
    - redis-master
  redis-sentinel:
    image: "redis:alpine"
    command: redis-server /data/sentinel-auth.conf --sentinel
    volumes:
      - ./auth/sentinel-auth.conf:/data/sentinel-auth.conf:rw
    depends_on:
    - redis-master
    - redis-slave
  redis-proxy:
    image: "findelabs/redis-rust-proxy:latest"
    environment:
    - LISTEN_ADDR=0.0.0.0:6379
    - MASTER_NAME=mymaster
    - SENTINEL_ADDR=redis-sentinel:26379
    - SENTINEL_TIMEOUT=1
    - REDIS_PASSWORD=test
    ports:
    - 6379:6379
    depends_on:
    - redis-sentinel
