version: "3.2"
services:
  redis-master:
    image: "redis:alpine"
    command: redis-server /data/redis.conf
    volumes:
      - ./master.conf:/data/redis.conf
  redis-slave:
    image: "redis:alpine"
    command: redis-server /data/redis.conf
    volumes:
      - ./slave.conf:/data/redis.conf
    depends_on:
    - redis-master
  redis-sentinel:
    image: "redis:alpine"
    command: redis-server /data/sentinel.conf --sentinel
    volumes:
      - ./sentinel.conf:/data/sentinel.conf:rw
    depends_on:
    - redis-master
    - redis-slave
  redis-proxy:
    image: "findelabs/redis-rust-proxy:latest"
    environment:
    - LISTEN_ADDR=0.0.0.0:6379
    - MASTER_NAME=mymaster
    - SENTINEL_ADDR=redis-sentinel:26379
    - SENTINEL_TIMEOUT=1
    ports:
    - 6379:6379
    depends_on:
    - redis-sentinel
